UNIVERSIDAD DE SAN CARLOS DE GUATEMALA
FACULTAD DE INGENIERÍA
ESCUELA DE ESTUDIOS DE POSTGRADO
MAESTRÍA EN INGENIERÍA PARA LA INDUSTRIA CON ESPECIALIZACIÓN EN CIENCIAS DE LA COMPUTACIÓN
CURSO: Fundamentos de Programación y Scripting
ESTUDIANTE: German Omar Chiguichón Sibrian

```{r}
library(dplyr)
library(ggplot2)
diamonds <- read.csv("diamonds.csv")
diamonds
str(diamonds)
```

1. DISPERSIÓN

```{r}
#1.1

ggplot(diamonds, aes(x=carat, y=price)) +
  geom_point()

#1.2 y #1.3

ggplot(diamonds, aes(x=carat, y=price, color=clarity)) +
  geom_point()
```

2. HISTOGRAMA

```{r}
#2.1

ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins=40)

#2.2

ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins=40)+
  scale_x_log10()
```

3. BOXPLOTS

```{r}
#3.1

ggplot(diamonds, aes(x=cut, y=price)) +
  geom_boxplot() +
  scale_y_log10()

#3.2

ggplot(diamonds, aes(x=cut, y=price, fill=cut)) +
  geom_boxplot() +
  scale_y_log10()
```

4. FACETING

```{r}
#4.1

filtered_price <- diamonds %>%
  filter(price > 1000)%>%
  filter(cut %in% c("Good", "Ideal", "Premium"))
filtered_price

#4.2

ggplot(filtered_price, aes(x=cut, y=depth)) + geom_col()

#4.3

ggplot(filtered_price, aes(x=cut, y=depth)) + geom_col()+
  facet_wrap(~ clarity)

#4.4

ggplot(filtered_price, aes(x=cut, y=depth, fill=clarity)) + geom_col()+
  facet_wrap(~ clarity)
```

GROUPING AND SUMMARIZING

```{r}
#1

median_dimension_diamond<-diamonds %>%
  group_by(cut) %>%
  summarize(mediaX = mean(x), mediaY = mean(y), mediaZ = mean(z))

median_dimension_diamond

#2

cut_premium<-diamonds %>%
  filter(cut=="Premium")%>%
  group_by(clarity) %>%
  summarize(minPrice = min(price), maxPrice = max(price))

cut_premium

#3

ggplot(cut_premium, aes(x=clarity, y=maxPrice, fill=clarity)) + geom_col()
```

